#!/usr/bin/env python
#
# Copyright 2012 Free Software Foundation, Inc.
#
# This file is part of GNU Radio
#
# GNU Radio is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# GNU Radio is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNU Radio; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street,
# Boston, MA 02110-1301, USA.
#

import os
import sys
from argparse import ArgumentParser
import warnings
warnings.simplefilter('ignore')

try:
    from grc.python.Platform import Platform
except ImportError:
    from gnuradio.grc.python.Platform import Platform


class GRCC:
    def __init__(self, grcfile, out_dir):
        self.out_dir = out_dir
        self.platform = Platform()
        data = self.platform.parse_flow_graph(grcfile)

        self.fg = self.platform.get_new_flow_graph()
        self.fg.import_data(data)
        self.fg.grc_file_path = os.path.abspath(grcfile)
        self.fg.validate()

        if not self.fg.is_valid():
            raise StandardError("\n\n".join(
                ["Validation failed:"] + self.fg.get_error_messages()
            ))

        self.gen = self.platform.get_generator()(self.fg, out_dir)
        self.gen.write()

    def exec_program(self):
        progname = self.fg.get_option('id')
        os.system("{0}/{1}.py".format(self.out_dir, progname))


def main():
    description = "Compiles a GRC file (.grc) into a GNU Radio Python program. The program is stored in ~/.grc_gnuradio by default, but this location can be changed with the -d option."

    parser = ArgumentParser(description=description)
    parser.add_argument("-d", "--directory",
            default='{0}/.grc_gnuradio/'.format(os.environ["HOME"]),
            help="Specify the directory to output the compile program [default=%(default)s]")
    parser.add_argument("-e", "--execute", action="store_true", default=False,
            help="Run the program after compiling [default=%(default)s]")
    parser.add_argument('grc_file', metavar="GRC_FILE", help=".grc file to compile")
    args = parser.parse_args()

    try:
        g = GRCC(args.grc_file, args.directory + "/")
    except Exception as e:
        sys.stderr.write(str(e) + "\n")
        sys.stderr.write("Error during file compilation.\n")
        sys.exit(1)

    if args.execute:
        g.exec_program()


if __name__ == "__main__":
    main()
