.TH GR_PLOT "1" "March 2019" "gr_plot 3.8" "User Commands"
.SH NAME
gr_plot \- display time series of samples from a file
.SH DESCRIPTION
Show data captured using the gnuradio file sink.
.PP
usage: gr_plot [\-h]
.IP
[\-d {complex64,float32,uint32,int32,uint16,int16,uint8,int8}]
[\-B BLOCK] [\-s START] [\-R SAMPLE_RATE]
FILE [FILE ...]
.PP
Takes a GNU Radio binary file and displays the samples versus time. You can
set the block size to specify how many points to read in at a time and the
start position in the file. By default, the system assumes a sample rate of 1,
so in time, each sample is plotted versus the sample number. To set a true
time axis, set the sample rate (\fB\-R\fR or \fB\-\-sample\-rate\fR) to the sample rate used
when capturing the samples.
.SS "positional arguments:"
.TP
FILE
Input file with samples
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-d\fR {complex64,float32,uint32,int32,uint16,int16,uint8,int8}, \fB\-\-data\-type\fR {complex64,float32,uint32,int32,uint16,int16,uint8,int8}
Specify the data type [default='complex64']
.TP
\fB\-B\fR BLOCK, \fB\-\-block\fR BLOCK
Specify the block size [default=1000]
.TP
\fB\-s\fR START, \fB\-\-start\fR START
Specify where to start in the file [default=0]
.TP
\fB\-R\fR SAMPLE_RATE, \fB\-\-sample\-rate\fR SAMPLE_RATE
Set the sampler rate of the data [default=1.0]
.SH "SEE ALSO"
gr_plot_char(1)  gr_plot_const(1)  gr_plot_fft_c(1)  gr_plot_fft_f(1)  gr_plot_float(1)  gr_plot_int(1)  gr_plot_iq(1)  gr_plot_psd_c(1)  gr_plot_psd_f(1)  gr_plot_qt(1)  gr_plot_short(1)
