/* volk_config.h.  Generated from volk_config.h.in by configure.  */
/*this file is auto generated by volk_register.py*/

#define LV_HAVE_GENERIC 1
/* #undef LV_HAVE_ORC */
/* #undef LV_HAVE_ALTIVEC */
/* #undef LV_HAVE_32 */
#define LV_HAVE_64 1
/* #undef LV_HAVE_3DNOW */
/* #undef LV_HAVE_ABM */
/* #undef LV_HAVE_POPCOUNT */
#define LV_HAVE_MMX 1
#define LV_HAVE_SSE 1
#define LV_HAVE_SSE2 1
#define LV_HAVE_SSE3 1
#define LV_HAVE_SSSE3 1
/* #undef LV_HAVE_SSE4_A */
#define LV_HAVE_SSE4_1 1
/* #undef LV_HAVE_SSE4_2 */
/* #undef LV_HAVE_AVX */

