# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_digital_window2.ui'
#
# Created: Sun Dec 20 22:08:51 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DigitalWindow(object):
    def setupUi(self, DigitalWindow):
        DigitalWindow.setObjectName("DigitalWindow")
        DigitalWindow.resize(1019, 754)
        self.centralwidget = QtGui.QWidget(DigitalWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pauseButton = QtGui.QPushButton(self.centralwidget)
        self.pauseButton.setMinimumSize(QtCore.QSize(80, 0))
        self.pauseButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pauseButton.setObjectName("pauseButton")
        self.verticalLayout.addWidget(self.pauseButton)
        spacerItem = QtGui.QSpacerItem(20, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.closeButton = QtGui.QPushButton(self.centralwidget)
        self.closeButton.setMinimumSize(QtCore.QSize(80, 0))
        self.closeButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout.addWidget(self.closeButton)
        self.gridLayout.addLayout(self.verticalLayout, 2, 5, 1, 1)
        self.channelModeBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelModeBox.sizePolicy().hasHeightForWidth())
        self.channelModeBox.setSizePolicy(sizePolicy)
        self.channelModeBox.setMinimumSize(QtCore.QSize(245, 130))
        self.channelModeBox.setMaximumSize(QtCore.QSize(245, 16777215))
        self.channelModeBox.setObjectName("channelModeBox")
        self.formLayoutWidget_2 = QtGui.QWidget(self.channelModeBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 221, 98))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.snrLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.snrLabel.setObjectName("snrLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.snrLabel)
        self.snrEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.snrEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.snrEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.snrEdit.setObjectName("snrEdit")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.snrEdit)
        self.freqLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.freqLabel.setObjectName("freqLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.freqLabel)
        self.freqEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.freqEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.freqEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.freqEdit.setObjectName("freqEdit")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.freqEdit)
        self.timeLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.timeLabel.setObjectName("timeLabel")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.timeLabel)
        self.timeEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.timeEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.timeEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.timeEdit.setObjectName("timeEdit")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.timeEdit)
        self.gridLayout.addWidget(self.channelModeBox, 2, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sysBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sysBox.sizePolicy().hasHeightForWidth())
        self.sysBox.setSizePolicy(sizePolicy)
        self.sysBox.setMinimumSize(QtCore.QSize(240, 60))
        self.sysBox.setMaximumSize(QtCore.QSize(240, 16777215))
        self.sysBox.setObjectName("sysBox")
        self.formLayoutWidget = QtGui.QWidget(self.sysBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 211, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.sampleRateEdit = QtGui.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleRateEdit.sizePolicy().hasHeightForWidth())
        self.sampleRateEdit.setSizePolicy(sizePolicy)
        self.sampleRateEdit.setMinimumSize(QtCore.QSize(60, 26))
        self.sampleRateEdit.setMaximumSize(QtCore.QSize(80, 26))
        self.sampleRateEdit.setObjectName("sampleRateEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.sampleRateEdit)
        self.sampleRateLabel = QtGui.QLabel(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleRateLabel.sizePolicy().hasHeightForWidth())
        self.sampleRateLabel.setSizePolicy(sizePolicy)
        self.sampleRateLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.sampleRateLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.sampleRateLabel.setObjectName("sampleRateLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.sampleRateLabel)
        self.verticalLayout_2.addWidget(self.sysBox)
        spacerItem1 = QtGui.QSpacerItem(20, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.rxBox_2 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rxBox_2.sizePolicy().hasHeightForWidth())
        self.rxBox_2.setSizePolicy(sizePolicy)
        self.rxBox_2.setMinimumSize(QtCore.QSize(220, 125))
        self.rxBox_2.setMaximumSize(QtCore.QSize(265, 125))
        self.rxBox_2.setObjectName("rxBox_2")
        self.formLayoutWidget_4 = QtGui.QWidget(self.rxBox_2)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 248, 188))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.pktsRcvdLabel = QtGui.QLabel(self.formLayoutWidget_4)
        self.pktsRcvdLabel.setObjectName("pktsRcvdLabel")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.pktsRcvdLabel)
        self.pktsRcvdEdit = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.pktsRcvdEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.pktsRcvdEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pktsRcvdEdit.setObjectName("pktsRcvdEdit")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.pktsRcvdEdit)
        self.pktsCorrectLabel = QtGui.QLabel(self.formLayoutWidget_4)
        self.pktsCorrectLabel.setObjectName("pktsCorrectLabel")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.pktsCorrectLabel)
        self.pktsCorrectEdit = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.pktsCorrectEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.pktsCorrectEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pktsCorrectEdit.setObjectName("pktsCorrectEdit")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.pktsCorrectEdit)
        self.perLabel = QtGui.QLabel(self.formLayoutWidget_4)
        self.perLabel.setObjectName("perLabel")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.perLabel)
        self.perEdit = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.perEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.perEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.perEdit.setObjectName("perEdit")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.perEdit)
        self.gridLayout.addWidget(self.rxBox_2, 2, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 4, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sinkFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sinkFrame.sizePolicy().hasHeightForWidth())
        self.sinkFrame.setSizePolicy(sizePolicy)
        self.sinkFrame.setMinimumSize(QtCore.QSize(500, 550))
        self.sinkFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sinkFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sinkFrame.setObjectName("sinkFrame")
        self.gridLayout_2 = QtGui.QGridLayout(self.sinkFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sinkLayout = QtGui.QHBoxLayout()
        self.sinkLayout.setObjectName("sinkLayout")
        self.gridLayout_2.addLayout(self.sinkLayout, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.sinkFrame)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 6)
        self.rxBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rxBox.sizePolicy().hasHeightForWidth())
        self.rxBox.setSizePolicy(sizePolicy)
        self.rxBox.setMinimumSize(QtCore.QSize(180, 120))
        self.rxBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.rxBox.setObjectName("rxBox")
        self.formLayoutWidget_3 = QtGui.QWidget(self.rxBox)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 161, 101))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.formLayout_3.setObjectName("formLayout_3")
        self.alphaTimeLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.alphaTimeLabel.setObjectName("alphaTimeLabel")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.alphaTimeLabel)
        self.alphaPhaseLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.alphaPhaseLabel.setObjectName("alphaPhaseLabel")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.alphaPhaseLabel)
        self.alphaTimeEdit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.alphaTimeEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.alphaTimeEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.alphaTimeEdit.setObjectName("alphaTimeEdit")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.alphaTimeEdit)
        self.alphaPhaseEdit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.alphaPhaseEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.alphaPhaseEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.alphaPhaseEdit.setObjectName("alphaPhaseEdit")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.alphaPhaseEdit)
        self.betaTimeEdit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.betaTimeEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.betaTimeEdit.setObjectName("betaTimeEdit")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.betaTimeEdit)
        self.betaTimeLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.betaTimeLabel.setObjectName("betaTimeLabel")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.betaTimeLabel)
        self.gridLayout.addWidget(self.rxBox, 2, 2, 1, 1)
        DigitalWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DigitalWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        DigitalWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DigitalWindow)
        self.statusbar.setObjectName("statusbar")
        DigitalWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(DigitalWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(DigitalWindow)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL("clicked()"), DigitalWindow.close)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), DigitalWindow.close)
        QtCore.QMetaObject.connectSlotsByName(DigitalWindow)
        DigitalWindow.setTabOrder(self.snrEdit, self.freqEdit)
        DigitalWindow.setTabOrder(self.freqEdit, self.timeEdit)

    def retranslateUi(self, DigitalWindow):
        DigitalWindow.setWindowTitle(QtGui.QApplication.translate("DigitalWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pauseButton.setText(QtGui.QApplication.translate("DigitalWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("DigitalWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.channelModeBox.setTitle(QtGui.QApplication.translate("DigitalWindow", "Channel Model Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.snrLabel.setText(QtGui.QApplication.translate("DigitalWindow", "SNR (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.freqLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Frequency Offset (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Timing Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.sysBox.setTitle(QtGui.QApplication.translate("DigitalWindow", "System Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleRateLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Sample Rate (sps)", None, QtGui.QApplication.UnicodeUTF8))
        self.rxBox_2.setTitle(QtGui.QApplication.translate("DigitalWindow", "Received Packet Info", None, QtGui.QApplication.UnicodeUTF8))
        self.pktsRcvdLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Packets Rcvd.", None, QtGui.QApplication.UnicodeUTF8))
        self.pktsCorrectLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Packets Correct", None, QtGui.QApplication.UnicodeUTF8))
        self.perLabel.setText(QtGui.QApplication.translate("DigitalWindow", "PER", None, QtGui.QApplication.UnicodeUTF8))
        self.rxBox.setTitle(QtGui.QApplication.translate("DigitalWindow", "Receiver Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.alphaTimeLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Alpha: time", None, QtGui.QApplication.UnicodeUTF8))
        self.alphaPhaseLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Alpha: phase", None, QtGui.QApplication.UnicodeUTF8))
        self.betaTimeLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Beta: time", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("DigitalWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("DigitalWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))

