# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_rx_window.ui'
#
# Created: Wed Jun 17 18:59:00 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DigitalWindow(object):
    def setupUi(self, DigitalWindow):
        DigitalWindow.setObjectName("DigitalWindow")
        DigitalWindow.resize(1085, 766)
        self.centralwidget = QtGui.QWidget(DigitalWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.closeButton = QtGui.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(960, 670, 101, 31))
        self.closeButton.setObjectName("closeButton")
        self.sinkFrame = QtGui.QFrame(self.centralwidget)
        self.sinkFrame.setGeometry(QtCore.QRect(10, 10, 1061, 501))
        self.sinkFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sinkFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sinkFrame.setObjectName("sinkFrame")
        self.horizontalLayoutWidget = QtGui.QWidget(self.sinkFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1041, 481))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.sinkLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.sinkLayout.setObjectName("sinkLayout")
        self.rxBox = QtGui.QGroupBox(self.centralwidget)
        self.rxBox.setGeometry(QtCore.QRect(10, 520, 251, 181))
        self.rxBox.setObjectName("rxBox")
        self.gainMuEdit = QtGui.QLineEdit(self.rxBox)
        self.gainMuEdit.setGeometry(QtCore.QRect(120, 120, 113, 23))
        self.gainMuEdit.setObjectName("gainMuEdit")
        self.gainMuLabel = QtGui.QLabel(self.rxBox)
        self.gainMuLabel.setGeometry(QtCore.QRect(10, 120, 111, 20))
        self.gainMuLabel.setObjectName("gainMuLabel")
        self.alphaEdit = QtGui.QLineEdit(self.rxBox)
        self.alphaEdit.setGeometry(QtCore.QRect(120, 150, 113, 23))
        self.alphaEdit.setObjectName("alphaEdit")
        self.alphaLabel = QtGui.QLabel(self.rxBox)
        self.alphaLabel.setGeometry(QtCore.QRect(10, 150, 111, 20))
        self.alphaLabel.setObjectName("alphaLabel")
        self.gainLabel = QtGui.QLabel(self.rxBox)
        self.gainLabel.setGeometry(QtCore.QRect(10, 60, 101, 17))
        self.gainLabel.setObjectName("gainLabel")
        self.freqEdit = QtGui.QLineEdit(self.rxBox)
        self.freqEdit.setGeometry(QtCore.QRect(120, 30, 113, 23))
        self.freqEdit.setObjectName("freqEdit")
        self.freqLabel = QtGui.QLabel(self.rxBox)
        self.freqLabel.setGeometry(QtCore.QRect(10, 30, 141, 17))
        self.freqLabel.setObjectName("freqLabel")
        self.gainEdit = QtGui.QLineEdit(self.rxBox)
        self.gainEdit.setGeometry(QtCore.QRect(120, 60, 113, 23))
        self.gainEdit.setObjectName("gainEdit")
        self.decimLabel = QtGui.QLabel(self.rxBox)
        self.decimLabel.setGeometry(QtCore.QRect(10, 90, 101, 17))
        self.decimLabel.setObjectName("decimLabel")
        self.decimEdit = QtGui.QLineEdit(self.rxBox)
        self.decimEdit.setGeometry(QtCore.QRect(120, 90, 113, 23))
        self.decimEdit.setObjectName("decimEdit")
        self.rxBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.rxBox_2.setGeometry(QtCore.QRect(300, 520, 251, 121))
        self.rxBox_2.setObjectName("rxBox_2")
        self.pktsRcvdEdit = QtGui.QLineEdit(self.rxBox_2)
        self.pktsRcvdEdit.setGeometry(QtCore.QRect(120, 30, 113, 23))
        self.pktsRcvdEdit.setObjectName("pktsRcvdEdit")
        self.pktsRcvdLabel = QtGui.QLabel(self.rxBox_2)
        self.pktsRcvdLabel.setGeometry(QtCore.QRect(10, 30, 111, 20))
        self.pktsRcvdLabel.setObjectName("pktsRcvdLabel")
        self.pktsCorrectEdit = QtGui.QLineEdit(self.rxBox_2)
        self.pktsCorrectEdit.setGeometry(QtCore.QRect(120, 60, 113, 23))
        self.pktsCorrectEdit.setObjectName("pktsCorrectEdit")
        self.pktsCorrectLabel = QtGui.QLabel(self.rxBox_2)
        self.pktsCorrectLabel.setGeometry(QtCore.QRect(10, 60, 111, 20))
        self.pktsCorrectLabel.setObjectName("pktsCorrectLabel")
        self.perLabel = QtGui.QLabel(self.rxBox_2)
        self.perLabel.setGeometry(QtCore.QRect(10, 90, 111, 20))
        self.perLabel.setObjectName("perLabel")
        self.perEdit = QtGui.QLineEdit(self.rxBox_2)
        self.perEdit.setGeometry(QtCore.QRect(120, 90, 113, 23))
        self.perEdit.setObjectName("perEdit")
        DigitalWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DigitalWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1085, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        DigitalWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DigitalWindow)
        self.statusbar.setObjectName("statusbar")
        DigitalWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(DigitalWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(DigitalWindow)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL("clicked()"), DigitalWindow.close)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), DigitalWindow.close)
        QtCore.QMetaObject.connectSlotsByName(DigitalWindow)

    def retranslateUi(self, DigitalWindow):
        DigitalWindow.setWindowTitle(QtGui.QApplication.translate("DigitalWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("DigitalWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.rxBox.setTitle(QtGui.QApplication.translate("DigitalWindow", "Receiver Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.gainMuLabel.setText(QtGui.QApplication.translate("DigitalWindow", "mu\'s gain", None, QtGui.QApplication.UnicodeUTF8))
        self.alphaLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.gainLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Gain (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.freqLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Frequency (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.decimLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Decimation", None, QtGui.QApplication.UnicodeUTF8))
        self.rxBox_2.setTitle(QtGui.QApplication.translate("DigitalWindow", "Received Packet Info", None, QtGui.QApplication.UnicodeUTF8))
        self.pktsRcvdLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Packets Rcvd.", None, QtGui.QApplication.UnicodeUTF8))
        self.pktsCorrectLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Packets Correct", None, QtGui.QApplication.UnicodeUTF8))
        self.perLabel.setText(QtGui.QApplication.translate("DigitalWindow", "PER", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("DigitalWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("DigitalWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))

