# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: jinja-yaml -*-

version: 2

jobs:
  build:
    working_directory: ~/test
    machine:
      image: ubuntu-2004:current
    steps:
      - run:
          # The Circle-CI build should not be active, but if this is not true for some reason, do a fast finish.
          command: exit 0

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /.*/
