/*
 * Copyright 2026 Analog Devices Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(event_monitor.h)                                          */
/* BINDTOOL_HEADER_FILE_HASH(293719e1dfcae551a3e70b81e54cd003)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iio/event_monitor.h>
// pydoc.h is automatically generated in the build directory
#include <event_monitor_pydoc.h>

void bind_event_monitor(py::module& m)
{

    using event_monitor = gr::iio::event_monitor;


    py::class_<event_monitor, gr::block, gr::basic_block, std::shared_ptr<event_monitor>>(
        m, "event_monitor", D(event_monitor))

        .def(py::init(&event_monitor::make),
             py::arg("uri"),
             py::arg("device"),
             D(event_monitor, make))

        ;
}
