# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_digital_window.ui'
#
# Created: Thu Jun 18 07:57:58 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DigitalWindow(object):
    def setupUi(self, DigitalWindow):
        DigitalWindow.setObjectName("DigitalWindow")
        DigitalWindow.resize(1236, 739)
        self.centralwidget = QtGui.QWidget(DigitalWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.closeButton = QtGui.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(1120, 650, 101, 31))
        self.closeButton.setObjectName("closeButton")
        self.sinkFrame = QtGui.QFrame(self.centralwidget)
        self.sinkFrame.setGeometry(QtCore.QRect(10, 10, 1221, 501))
        self.sinkFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sinkFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sinkFrame.setObjectName("sinkFrame")
        self.horizontalLayoutWidget = QtGui.QWidget(self.sinkFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1201, 481))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.sinkLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.sinkLayout.setObjectName("sinkLayout")
        self.channelModeBox = QtGui.QGroupBox(self.centralwidget)
        self.channelModeBox.setGeometry(QtCore.QRect(290, 520, 291, 161))
        self.channelModeBox.setObjectName("channelModeBox")
        self.timeLabel = QtGui.QLabel(self.channelModeBox)
        self.timeLabel.setGeometry(QtCore.QRect(10, 90, 101, 17))
        self.timeLabel.setObjectName("timeLabel")
        self.timeEdit = QtGui.QLineEdit(self.channelModeBox)
        self.timeEdit.setGeometry(QtCore.QRect(160, 90, 113, 23))
        self.timeEdit.setObjectName("timeEdit")
        self.snrEdit = QtGui.QLineEdit(self.channelModeBox)
        self.snrEdit.setGeometry(QtCore.QRect(160, 30, 113, 23))
        self.snrEdit.setObjectName("snrEdit")
        self.snrLabel = QtGui.QLabel(self.channelModeBox)
        self.snrLabel.setGeometry(QtCore.QRect(10, 30, 111, 20))
        self.snrLabel.setObjectName("snrLabel")
        self.freqEdit = QtGui.QLineEdit(self.channelModeBox)
        self.freqEdit.setGeometry(QtCore.QRect(160, 60, 113, 23))
        self.freqEdit.setObjectName("freqEdit")
        self.freqLabel = QtGui.QLabel(self.channelModeBox)
        self.freqLabel.setGeometry(QtCore.QRect(10, 60, 141, 17))
        self.freqLabel.setObjectName("freqLabel")
        self.rxBox = QtGui.QGroupBox(self.centralwidget)
        self.rxBox.setGeometry(QtCore.QRect(590, 520, 251, 161))
        self.rxBox.setObjectName("rxBox")
        self.gainMuEdit = QtGui.QLineEdit(self.rxBox)
        self.gainMuEdit.setGeometry(QtCore.QRect(120, 30, 113, 23))
        self.gainMuEdit.setObjectName("gainMuEdit")
        self.gainMuLabel = QtGui.QLabel(self.rxBox)
        self.gainMuLabel.setGeometry(QtCore.QRect(10, 30, 111, 20))
        self.gainMuLabel.setObjectName("gainMuLabel")
        self.alphaEdit = QtGui.QLineEdit(self.rxBox)
        self.alphaEdit.setGeometry(QtCore.QRect(120, 60, 113, 23))
        self.alphaEdit.setObjectName("alphaEdit")
        self.alphaLabel = QtGui.QLabel(self.rxBox)
        self.alphaLabel.setGeometry(QtCore.QRect(10, 60, 111, 20))
        self.alphaLabel.setObjectName("alphaLabel")
        self.sysBox = QtGui.QGroupBox(self.centralwidget)
        self.sysBox.setGeometry(QtCore.QRect(20, 520, 261, 161))
        self.sysBox.setObjectName("sysBox")
        self.sampleRateEdit = QtGui.QLineEdit(self.sysBox)
        self.sampleRateEdit.setGeometry(QtCore.QRect(140, 30, 113, 23))
        self.sampleRateEdit.setObjectName("sampleRateEdit")
        self.sampleRateLabel = QtGui.QLabel(self.sysBox)
        self.sampleRateLabel.setGeometry(QtCore.QRect(10, 30, 121, 20))
        self.sampleRateLabel.setObjectName("sampleRateLabel")
        self.pauseButton = QtGui.QPushButton(self.centralwidget)
        self.pauseButton.setGeometry(QtCore.QRect(1120, 520, 101, 31))
        self.pauseButton.setObjectName("pauseButton")
        DigitalWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DigitalWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1236, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        DigitalWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DigitalWindow)
        self.statusbar.setObjectName("statusbar")
        DigitalWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(DigitalWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(DigitalWindow)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL("clicked()"), DigitalWindow.close)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), DigitalWindow.close)
        QtCore.QMetaObject.connectSlotsByName(DigitalWindow)
        DigitalWindow.setTabOrder(self.closeButton, self.snrEdit)
        DigitalWindow.setTabOrder(self.snrEdit, self.freqEdit)
        DigitalWindow.setTabOrder(self.freqEdit, self.timeEdit)

    def retranslateUi(self, DigitalWindow):
        DigitalWindow.setWindowTitle(QtGui.QApplication.translate("DigitalWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("DigitalWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.channelModeBox.setTitle(QtGui.QApplication.translate("DigitalWindow", "Channel Model Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Timing Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.snrLabel.setText(QtGui.QApplication.translate("DigitalWindow", "SNR (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.freqLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Frequency Offset (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.rxBox.setTitle(QtGui.QApplication.translate("DigitalWindow", "Receiver Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.gainMuLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Gain mu", None, QtGui.QApplication.UnicodeUTF8))
        self.alphaLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.sysBox.setTitle(QtGui.QApplication.translate("DigitalWindow", "System Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleRateLabel.setText(QtGui.QApplication.translate("DigitalWindow", "Sample Rate (sps)", None, QtGui.QApplication.UnicodeUTF8))
        self.pauseButton.setText(QtGui.QApplication.translate("DigitalWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("DigitalWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("DigitalWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))

