/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/wavelet/wavelet_ff.h>
// pydoc.h is automatically generated in the build directory
#include <wavelet_ff_pydoc.h>

void bind_wavelet_ff(py::module& m)
{

    using wavelet_ff = ::gr::wavelet::wavelet_ff;


    py::class_<wavelet_ff,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<wavelet_ff>>(m, "wavelet_ff", D(wavelet_ff))

        .def(py::init(&wavelet_ff::make),
             py::arg("size") = 1024,
             py::arg("order") = 20,
             py::arg("forward") = true,
             D(wavelet_ff, make))


        ;
}
