#!/bin/sh

# Copyright 2001-2011 Free Software Foundation, Inc.
# 
# This file is part of GNU Radio
# 
# GNU Radio is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
# 
# GNU Radio is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with GNU Radio; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street,
# Boston, MA 02110-1301, USA.

srcdir=$(cd $(dirname $0) ; pwd)
gendir=${srcdir}/gen

echo "Bootstrap'n volk... ${srcdir}"

python -B ${srcdir}/gen/volk_register.py
mv ${gendir}/lib/Makefile.am ${srcdir}/lib/

(cd ${srcdir} ; rm -fr config.cache autom4te*.cache)
(cd ${srcdir} ; aclocal -I config -I ${gendir}/config)
(cd ${srcdir} ; autoconf)
(cd ${srcdir} ; autoheader)
(cd ${srcdir} ; libtoolize --automake)
(cd ${srcdir} ; automake --add-missing -Wno-portability -Wno-override -Wnone)

