/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(scrambler_bb.h)                                            */
/* BINDTOOL_HEADER_FILE_HASH(83d0f3673216d2c2d68b1833512e01e2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/scrambler_bb.h>
// pydoc.h is automatically generated in the build directory
#include <scrambler_bb_pydoc.h>

void bind_scrambler_bb(py::module& m)
{

    using scrambler_bb = ::gr::digital::scrambler_bb;


    py::class_<scrambler_bb,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<scrambler_bb>>(m, "scrambler_bb", D(scrambler_bb))

        .def(py::init(&scrambler_bb::make),
             py::arg("mask"),
             py::arg("seed"),
             py::arg("len"),
             D(scrambler_bb, make))


        ;
}
