/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digital/simple_correlator.h>
// pydoc.h is automatically generated in the build directory
#include <simple_correlator_pydoc.h>

void bind_simple_correlator(py::module& m)
{

    using simple_correlator = ::gr::digital::simple_correlator;


    py::class_<simple_correlator,
               gr::block,
               gr::basic_block,
               std::shared_ptr<simple_correlator>>(
        m, "simple_correlator", D(simple_correlator))

        .def(py::init(&simple_correlator::make),
             py::arg("payload_bytesize"),
             D(simple_correlator, make))


        ;
}
