/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(port_names.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(22a69101edc6be4884266ea9be55a844)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/message/port_names.h>
// pydoc.h is automatically generated in the build directory
#include <port_names_pydoc.h>

void bind_port_names(py::module& m)
{


    m.def("PMTCONSTSTR__emit", &::gr::message::PMTCONSTSTR__emit, D(PMTCONSTSTR__emit));


    m.def("PMTCONSTSTR__msg", &::gr::message::PMTCONSTSTR__msg, D(PMTCONSTSTR__msg));
}
