#!/usr/bin/env python

from gnuradio import gr
from gnuradio import usrp
from optparse import OptionParser
import usrp_dbid

u_source = usrp.source_c()
u_sink = usrp.sink_c()
subdev_Ar = usrp.selected_subdev(u_source, (0,0))
subdev_Br = usrp.selected_subdev(u_source, (1,0))
subdev_At = usrp.selected_subdev(u_sink, (0,0))
subdev_Bt = usrp.selected_subdev(u_sink, (1,0))

print "RX d'board %s" % (subdev_Ar.side_and_name(),)
print "RX d'board %s" % (subdev_Br.side_and_name(),)
print "TX d'board %s" % (subdev_At.side_and_name(),)
print "TX d'board %s" % (subdev_Bt.side_and_name(),)

