# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_wfm_interface.ui'
#
# Created: Thu Jun 18 23:41:03 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_InterfaceWindow(object):
    def setupUi(self, InterfaceWindow):
        InterfaceWindow.setObjectName("InterfaceWindow")
        InterfaceWindow.resize(909, 711)
        self.centralwidget = QtGui.QWidget(InterfaceWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.closeButton = QtGui.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(790, 580, 101, 31))
        self.closeButton.setObjectName("closeButton")
        self.sinkFrame = QtGui.QFrame(self.centralwidget)
        self.sinkFrame.setGeometry(QtCore.QRect(10, 10, 891, 501))
        self.sinkFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sinkFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sinkFrame.setObjectName("sinkFrame")
        self.horizontalLayoutWidget = QtGui.QWidget(self.sinkFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 871, 481))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.sinkLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.sinkLayout.setObjectName("sinkLayout")
        self.channelModeBox = QtGui.QGroupBox(self.centralwidget)
        self.channelModeBox.setGeometry(QtCore.QRect(10, 520, 261, 131))
        self.channelModeBox.setObjectName("channelModeBox")
        self.bandwidthabel = QtGui.QLabel(self.channelModeBox)
        self.bandwidthabel.setGeometry(QtCore.QRect(10, 90, 101, 17))
        self.bandwidthabel.setObjectName("bandwidthabel")
        self.bandwidthEdit = QtGui.QLineEdit(self.channelModeBox)
        self.bandwidthEdit.setGeometry(QtCore.QRect(130, 90, 113, 23))
        self.bandwidthEdit.setObjectName("bandwidthEdit")
        self.gainEdit = QtGui.QLineEdit(self.channelModeBox)
        self.gainEdit.setGeometry(QtCore.QRect(130, 60, 113, 23))
        self.gainEdit.setObjectName("gainEdit")
        self.gainLabel = QtGui.QLabel(self.channelModeBox)
        self.gainLabel.setGeometry(QtCore.QRect(10, 60, 111, 20))
        self.gainLabel.setObjectName("gainLabel")
        self.freqEdit = QtGui.QLineEdit(self.channelModeBox)
        self.freqEdit.setGeometry(QtCore.QRect(130, 30, 113, 23))
        self.freqEdit.setObjectName("freqEdit")
        self.freqLabel = QtGui.QLabel(self.channelModeBox)
        self.freqLabel.setGeometry(QtCore.QRect(10, 30, 111, 17))
        self.freqLabel.setObjectName("freqLabel")
        self.pauseButton = QtGui.QPushButton(self.centralwidget)
        self.pauseButton.setGeometry(QtCore.QRect(790, 520, 101, 31))
        self.pauseButton.setObjectName("pauseButton")
        self.fmBox = QtGui.QGroupBox(self.centralwidget)
        self.fmBox.setGeometry(QtCore.QRect(290, 520, 251, 131))
        self.fmBox.setObjectName("fmBox")
        self.volumeEdit = QtGui.QLineEdit(self.fmBox)
        self.volumeEdit.setGeometry(QtCore.QRect(130, 20, 113, 23))
        self.volumeEdit.setObjectName("volumeEdit")
        self.volumeLabel = QtGui.QLabel(self.fmBox)
        self.volumeLabel.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.volumeLabel.setObjectName("volumeLabel")
        InterfaceWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(InterfaceWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 909, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        InterfaceWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(InterfaceWindow)
        self.statusbar.setObjectName("statusbar")
        InterfaceWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(InterfaceWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(InterfaceWindow)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL("clicked()"), InterfaceWindow.close)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), InterfaceWindow.close)
        QtCore.QMetaObject.connectSlotsByName(InterfaceWindow)
        InterfaceWindow.setTabOrder(self.closeButton, self.gainEdit)
        InterfaceWindow.setTabOrder(self.gainEdit, self.freqEdit)
        InterfaceWindow.setTabOrder(self.freqEdit, self.bandwidthEdit)

    def retranslateUi(self, InterfaceWindow):
        InterfaceWindow.setWindowTitle(QtGui.QApplication.translate("InterfaceWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("InterfaceWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.channelModeBox.setTitle(QtGui.QApplication.translate("InterfaceWindow", "USRP Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.bandwidthabel.setText(QtGui.QApplication.translate("InterfaceWindow", "Bandwidth (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.gainLabel.setText(QtGui.QApplication.translate("InterfaceWindow", "Gain (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.freqLabel.setText(QtGui.QApplication.translate("InterfaceWindow", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.pauseButton.setText(QtGui.QApplication.translate("InterfaceWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.fmBox.setTitle(QtGui.QApplication.translate("InterfaceWindow", "FM Tuner Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeLabel.setText(QtGui.QApplication.translate("InterfaceWindow", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("InterfaceWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("InterfaceWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))

