/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtv/atsc_randomizer.h>
// pydoc.h is automatically generated in the build directory
#include <atsc_randomizer_pydoc.h>

void bind_atsc_randomizer(py::module& m)
{

    using atsc_randomizer = ::gr::dtv::atsc_randomizer;


    py::class_<atsc_randomizer,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<atsc_randomizer>>(m, "atsc_randomizer", D(atsc_randomizer))

        .def(py::init(&atsc_randomizer::make), D(atsc_randomizer, make))


        ;
}
