/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(atsc_randomizer.h)                                         */
/* BINDTOOL_HEADER_FILE_HASH(76ffed0a2e924572e06035fd164a8f0d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtv/atsc_randomizer.h>
// pydoc.h is automatically generated in the build directory
#include <atsc_randomizer_pydoc.h>

void bind_atsc_randomizer(py::module& m)
{

    using atsc_randomizer = ::gr::dtv::atsc_randomizer;


    py::class_<atsc_randomizer,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<atsc_randomizer>>(m, "atsc_randomizer", D(atsc_randomizer))

        .def(py::init(&atsc_randomizer::make), D(atsc_randomizer, make))


        ;
}
