/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dvbt2_modulator_bc.h)                                      */
/* BINDTOOL_HEADER_FILE_HASH(0aa462ecd69deb5ea7b88a14f4a7c810)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dtv/dvbt2_modulator_bc.h>
// pydoc.h is automatically generated in the build directory
#include <dvbt2_modulator_bc_pydoc.h>

void bind_dvbt2_modulator_bc(py::module& m)
{

    using dvbt2_modulator_bc = ::gr::dtv::dvbt2_modulator_bc;


    py::class_<dvbt2_modulator_bc,
               gr::block,
               gr::basic_block,
               std::shared_ptr<dvbt2_modulator_bc>>(
        m, "dvbt2_modulator_bc", D(dvbt2_modulator_bc))

        .def(py::init(&dvbt2_modulator_bc::make),
             py::arg("framesize"),
             py::arg("constellation"),
             py::arg("rotation"),
             D(dvbt2_modulator_bc, make))


        ;
}
