channel_targets:
  - gnuradio main
c_compiler:    # [win]
- vs2022       # [win]
cxx_compiler:  # [win]
- vs2022       # [win]
libboost_devel:
- '1.90'
libboost_headers:
- '1.90'
libboost_python_devel:
- '1.90'
