/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/complex_to_magphase.h>
// pydoc.h is automatically generated in the build directory
#include <complex_to_magphase_pydoc.h>

void bind_complex_to_magphase(py::module& m)
{

    using complex_to_magphase = ::gr::blocks::complex_to_magphase;


    py::class_<complex_to_magphase,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<complex_to_magphase>>(
        m, "complex_to_magphase", D(complex_to_magphase))

        .def(py::init(&complex_to_magphase::make),
             py::arg("vlen") = 1,
             D(complex_to_magphase, make))


        ;
}
