/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/short_to_char.h>
// pydoc.h is automatically generated in the build directory
#include <short_to_char_pydoc.h>

void bind_short_to_char(py::module& m)
{

    using short_to_char = ::gr::blocks::short_to_char;


    py::class_<short_to_char,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<short_to_char>>(m, "short_to_char", D(short_to_char))

        .def(py::init(&short_to_char::make), py::arg("vlen") = 1, D(short_to_char, make))


        ;
}
