/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/skiphead.h>
// pydoc.h is automatically generated in the build directory
#include <skiphead_pydoc.h>

void bind_skiphead(py::module& m)
{

    using skiphead = ::gr::blocks::skiphead;


    py::class_<skiphead, gr::block, gr::basic_block, std::shared_ptr<skiphead>>(
        m, "skiphead", D(skiphead))

        .def(py::init(&skiphead::make),
             py::arg("itemsize"),
             py::arg("nitems_to_skip"),
             D(skiphead, make))


        ;
}
