/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(streams_to_vector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(84587c2f1f7b6ec1a8f0da19a06555cc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/streams_to_vector.h>
// pydoc.h is automatically generated in the build directory
#include <streams_to_vector_pydoc.h>

void bind_streams_to_vector(py::module& m)
{

    using streams_to_vector = ::gr::blocks::streams_to_vector;


    py::class_<streams_to_vector,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<streams_to_vector>>(
        m, "streams_to_vector", D(streams_to_vector))

        .def(py::init(&streams_to_vector::make),
             py::arg("itemsize"),
             py::arg("nstreams"),
             D(streams_to_vector, make))


        ;
}
