/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/blocks/uchar_to_float.h>
// pydoc.h is automatically generated in the build directory
#include <uchar_to_float_pydoc.h>

void bind_uchar_to_float(py::module& m)
{

    using uchar_to_float = ::gr::blocks::uchar_to_float;


    py::class_<uchar_to_float,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<uchar_to_float>>(m, "uchar_to_float", D(uchar_to_float))

        .def(py::init(&uchar_to_float::make), D(uchar_to_float, make))


        ;
}
