INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_THRIFT thrift>=0.9.2)

FIND_PATH(THRIFT_INCLUDE_DIRS
    NAMES thrift/Thrift.h
    HINTS ${PC_THRIFT_INCLUDE_DIR}
    ${CMAKE_INSTALL_PREFIX}/include
    PATHS
    /usr/local/include
    /usr/include
)

FIND_LIBRARY(THRIFT_LIBRARIES
    NAMES thrift
    HINTS ${PC_THRIFT_LIBDIR}
    ${CMAKE_INSTALL_PREFIX}/lib
    ${CMAKE_INSTALL_PREFIX}/lib64
    PATHS
    ${THRIFT_INCLUDE_DIRS}/../lib
    /usr/local/lib
    /usr/lib
)

if(THRIFT_INCLUDE_DIRS AND THRIFT_LIBRARIES)
  set(THRIFT_FOUND TRUE CACHE BOOL "If Thift has been found")
endif(THRIFT_INCLUDE_DIRS AND THRIFT_LIBRARIES)


# Get the thrift binary to build our files during cmake
FIND_PROGRAM(THRIFT_BIN thrift)

# Check that Thrift for Python is available
include(GrPython)
GR_PYTHON_CHECK_MODULE("Thrift" thrift "1" PYTHON_THRIFT_FOUND)

if(NOT PYTHON_THRIFT_FOUND)
  unset(THRIFT_FOUND)
endif(NOT PYTHON_THRIFT_FOUND)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(THRIFT DEFAULT_MSG
  THRIFT_LIBRARIES THRIFT_INCLUDE_DIRS
  THRIFT_BIN PYTHON_THRIFT_FOUND THRIFT_FOUND
)
MARK_AS_ADVANCED(
  THRIFT_LIBRARIES THRIFT_INCLUDE_DIRS
  THRIFT_BIN PYTHON_THRIFT_FOUND THRIFT_FOUND
)
