# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt_filter.ui'
#
# Created: Tue Aug 18 22:48:21 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 696)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabGroup = QtGui.QTabWidget(self.centralwidget)
        self.tabGroup.setMinimumSize(QtCore.QSize(800, 0))
        self.tabGroup.setObjectName("tabGroup")
        self.freqTab = QtGui.QWidget()
        self.freqTab.setObjectName("freqTab")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.freqTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.freqPlot = Qwt5.QwtPlot(self.freqTab)
        self.freqPlot.setObjectName("freqPlot")
        self.horizontalLayout_2.addWidget(self.freqPlot)
        self.tabGroup.addTab(self.freqTab, "")
        self.timeTab = QtGui.QWidget()
        self.timeTab.setObjectName("timeTab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.timeTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timePlot = Qwt5.QwtPlot(self.timeTab)
        self.timePlot.setObjectName("timePlot")
        self.horizontalLayout.addWidget(self.timePlot)
        self.tabGroup.addTab(self.timeTab, "")
        self.gridLayout.addWidget(self.tabGroup, 1, 1, 1, 1)
        self.filterFrame = QtGui.QFrame(self.centralwidget)
        self.filterFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.filterFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.filterFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.filterFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.filterFrame.setObjectName("filterFrame")
        self.verticalLayout = QtGui.QVBoxLayout(self.filterFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filterTypeComboBox = QtGui.QComboBox(self.filterFrame)
        self.filterTypeComboBox.setObjectName("filterTypeComboBox")
        self.filterTypeComboBox.addItem(QtCore.QString())
        self.filterTypeComboBox.addItem(QtCore.QString())
        self.filterTypeComboBox.addItem(QtCore.QString())
        self.filterTypeComboBox.addItem(QtCore.QString())
        self.filterTypeComboBox.addItem(QtCore.QString())
        self.filterTypeComboBox.addItem(QtCore.QString())
        self.filterTypeComboBox.addItem(QtCore.QString())
        self.verticalLayout.addWidget(self.filterTypeComboBox)
        self.filterDesignTypeComboBox = QtGui.QComboBox(self.filterFrame)
        self.filterDesignTypeComboBox.setObjectName("filterDesignTypeComboBox")
        self.filterDesignTypeComboBox.addItem(QtCore.QString())
        self.filterDesignTypeComboBox.addItem(QtCore.QString())
        self.verticalLayout.addWidget(self.filterDesignTypeComboBox)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.sampleRateLabel = QtGui.QLabel(self.filterFrame)
        self.sampleRateLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sampleRateLabel.setObjectName("sampleRateLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.sampleRateLabel)
        self.sampleRateEdit = QtGui.QLineEdit(self.filterFrame)
        self.sampleRateEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sampleRateEdit.setObjectName("sampleRateEdit")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.sampleRateEdit)
        self.filterGainLabel = QtGui.QLabel(self.filterFrame)
        self.filterGainLabel.setObjectName("filterGainLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.filterGainLabel)
        self.filterGainEdit = QtGui.QLineEdit(self.filterFrame)
        self.filterGainEdit.setObjectName("filterGainEdit")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.filterGainEdit)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.filterTypeWidget = QtGui.QStackedWidget(self.filterFrame)
        self.filterTypeWidget.setObjectName("filterTypeWidget")
        self.firlpfPage = QtGui.QWidget()
        self.firlpfPage.setObjectName("firlpfPage")
        self.filterTypeWidget.addWidget(self.firlpfPage)
        self.firhpfPage = QtGui.QWidget()
        self.firhpfPage.setObjectName("firhpfPage")
        self.filterTypeWidget.addWidget(self.firhpfPage)
        self.verticalLayout.addWidget(self.filterTypeWidget)
        self.designButton = QtGui.QPushButton(self.filterFrame)
        self.designButton.setMinimumSize(QtCore.QSize(0, 0))
        self.designButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.designButton.setObjectName("designButton")
        self.verticalLayout.addWidget(self.designButton)
        self.gridLayout.addWidget(self.filterFrame, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 624, 25))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtGui.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.menu_File.addAction(self.action_exit)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        self.tabGroup.setCurrentIndex(0)
        QtCore.QObject.connect(self.action_exit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.filterTypeComboBox, self.filterDesignTypeComboBox)
        MainWindow.setTabOrder(self.filterDesignTypeComboBox, self.sampleRateEdit)
        MainWindow.setTabOrder(self.sampleRateEdit, self.filterGainEdit)
        MainWindow.setTabOrder(self.filterGainEdit, self.designButton)
        MainWindow.setTabOrder(self.designButton, self.tabGroup)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabGroup.setTabText(self.tabGroup.indexOf(self.freqTab), QtGui.QApplication.translate("MainWindow", "Frequency Domain", None, QtGui.QApplication.UnicodeUTF8))
        self.tabGroup.setTabText(self.tabGroup.indexOf(self.timeTab), QtGui.QApplication.translate("MainWindow", "Time Domain", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTypeComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Low Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTypeComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Band Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTypeComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Complex Band Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTypeComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Band Notch", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTypeComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "High Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTypeComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Root Raised Cosine", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTypeComboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.filterDesignTypeComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Windowed", None, QtGui.QApplication.UnicodeUTF8))
        self.filterDesignTypeComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Equiripple", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleRateLabel.setText(QtGui.QApplication.translate("MainWindow", "Sample Rate (sps)", None, QtGui.QApplication.UnicodeUTF8))
        self.filterGainLabel.setText(QtGui.QApplication.translate("MainWindow", "Filter Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.designButton.setText(QtGui.QApplication.translate("MainWindow", "Design", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5
