/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(decode_ccsds_27_fb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(dd6c1aedf09ee458ddfb8d457055086d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fec/decode_ccsds_27_fb.h>
// pydoc.h is automatically generated in the build directory
#include <decode_ccsds_27_fb_pydoc.h>

void bind_decode_ccsds_27_fb(py::module& m)
{

    using decode_ccsds_27_fb = ::gr::fec::decode_ccsds_27_fb;


    py::class_<decode_ccsds_27_fb,
               gr::sync_decimator,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<decode_ccsds_27_fb>>(
        m, "decode_ccsds_27_fb", D(decode_ccsds_27_fb))

        .def(py::init(&decode_ccsds_27_fb::make), D(decode_ccsds_27_fb, make))


        ;
}
