name: Check PR Formatting

on:
  pull_request:
    paths:
      - '!volk/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: gnuradio/clang-format-lint-action@v0.5-1
      with:
        source: '.'
        exclude: './volk'
        extensions: 'h,hpp,cpp,cc'
        clangFormatVersion: 7
