# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

name: Build conda package
on:
  push:
    branches:
      - main

  pull_request:


jobs:
  build:
    name: ${{ matrix.CONFIG }}
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      max-parallel: 50
      matrix:
        include:
          - CONFIG: linux_64_python3.11.____cpython
            CONFIG_SHORT: linux_64_python3.11.____cpython
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:cos7
            STORE_BUILD_ARTIFACTS: True
            UPLOAD_PACKAGES: True
            build_workspace_dir: build_artifacts
            docker_run_args: 
            free_disk_space: skip
            os: ubuntu
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['ubuntu-latest']
            tools_install_dir: ~/miniforge3
          - CONFIG: osx_arm64_python3.11.____cpython
            CONFIG_SHORT: osx_arm64_python3.11.____cpython
            STORE_BUILD_ARTIFACTS: True
            UPLOAD_PACKAGES: True
            build_workspace_dir: ~/miniforge3/conda-bld
            docker_run_args: 
            free_disk_space: skip
            os: macos
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['macos-15']
            tools_install_dir: ~/miniforge3
          - CONFIG: win_64_python3.11.____cpython
            CONFIG_SHORT: win_64_python3.11.____cpython
            STORE_BUILD_ARTIFACTS: True
            UPLOAD_PACKAGES: True
            build_platform: win-64
            build_workspace_dir: D:\\bld\\
            docker_run_args: 
            free_disk_space: skip
            os: windows
            pagefile_size: 0
            resize_partitions: False
            runs_on: ['windows-2022']
            tools_install_dir: D:\Miniforge
    steps:

    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
    - name: Configure binfmt_misc
      if: matrix.os == 'ubuntu'
      shell: bash
      run: |
        if [[ "$(uname -m)" == "x86_64" ]]; then
          docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
        fi

    - name: Build on Linux
      id: build-linux
      if: matrix.os == 'ubuntu'
      env:
        CI: github_actions
        CONDA_BLD_PATH: ${{ matrix.build_workspace_dir }}
        CONDA_FORGE_DOCKER_RUN_ARGS: ${{ matrix.docker_run_args }}
        CONFIG: ${{ matrix.CONFIG }}
        MINIFORGE_HOME: ${{ matrix.tools_install_dir }}
        DOCKER_IMAGE: ${{ matrix.DOCKER_IMAGE }}
        UPLOAD_ON_BRANCH: main
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        RATTLER_BUILD_COLOR: always
        RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: 'true'
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
      shell: bash
      run: |
        export CONDA_BLD_PATH="${CONDA_BLD_PATH/#~/${HOME}}"
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="${GITHUB_REF_NAME}"
        export MINIFORGE_HOME="${MINIFORGE_HOME/#~/${HOME}}"
        export flow_run_id="github_$GITHUB_RUN_ID"
        export remote_url="https://github.com/$GITHUB_REPOSITORY"
        export sha="$GITHUB_SHA"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        ./.scripts/run_docker_build.sh

    - name: Build on macOS
      id: build-macos
      if: matrix.os == 'macos'
      env:
        CI: github_actions
        CONDA_BLD_PATH: ${{ matrix.build_workspace_dir }}
        CONFIG: ${{ matrix.CONFIG }}
        MINIFORGE_HOME: ${{ matrix.tools_install_dir }}
        UPLOAD_ON_BRANCH: main
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        RATTLER_BUILD_COLOR: always
        RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: 'true'
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
      shell: bash
      run: |
        export CONDA_BLD_PATH="${CONDA_BLD_PATH/#~/${HOME}}"
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="${GITHUB_REF_NAME}"
        export MINIFORGE_HOME="${MINIFORGE_HOME/#~/${HOME}}"
        export flow_run_id="github_$GITHUB_RUN_ID"
        export remote_url="https://github.com/$GITHUB_REPOSITORY"
        export sha="$GITHUB_SHA"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        ./.scripts/run_osx_build.sh

    - name: Build on windows
      id: build-windows
      if: matrix.os == 'windows'
      shell: cmd
      run: |
        set "flow_run_id=github_%GITHUB_RUN_ID%"
        set "remote_url=https://github.com/%GITHUB_REPOSITORY%"
        set "sha=%GITHUB_SHA%"
        call ".scripts\run_win_build.bat"
      env:
        BUILD_PLATFORM: ${{ matrix.build_platform }}
        CI: github_actions
        CONDA_BLD_PATH: ${{ matrix.build_workspace_dir }}
        CONFIG: ${{ matrix.CONFIG }}
        MINIFORGE_HOME: ${{ matrix.tools_install_dir }}
        PYTHONUNBUFFERED: 1
        UPLOAD_ON_BRANCH: main
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        RATTLER_BUILD_COLOR: always
        RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: 'true'
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}

    - name: Determine build outcome
      # this is to merge the status of the linux/osx/win builds into
      # something we can easily reuse during artefact generation
      id: determine-status
      if: ${{ always() }}
      shell: bash
      env:
        OS: ${{ matrix.os }}
      run: |
        if [[ "$OS" == "ubuntu" ]]; then
          STATUS=${{ steps.build-linux.outcome }}
        elif [[ "$OS" == "macos" ]]; then
          STATUS=${{ steps.build-macos.outcome }}
        elif [[ "$OS" == "windows" ]]; then
          STATUS=${{ steps.build-windows.outcome }}
        fi
        if [ -z "$STATUS" ]; then
          # steps that never ran will have empty status
          STATUS="cancelled"
        fi
        echo "status=$STATUS" >> $GITHUB_OUTPUT

    - name: Prepare conda build artifacts
      continue-on-error: true
      id: prepare-artifacts
      shell: bash
      # we do not want to trigger artefact creation if the build was cancelled
      if: ${{ always() && steps.determine-status.outputs.status != 'cancelled' && matrix.STORE_BUILD_ARTIFACTS }}
      env:
        CI: github_actions
        CONDA_BLD_PATH: ${{ matrix.build_workspace_dir }}
        CONFIG: ${{ matrix.CONFIG }}
        CONFIG_SHORT: ${{ matrix.CONFIG_SHORT }}
        JOB_STATUS: ${{ steps.determine-status.outputs.status }}
        OS: ${{ matrix.os }}
      run: |
        export ARTIFACT_STAGING_DIR="$GITHUB_WORKSPACE"
        export CI_RUN_ID=$GITHUB_RUN_ID
        export CONDA_BLD_PATH="${CONDA_BLD_PATH/#~/${HOME}}"
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export MINIFORGE_HOME="${MINIFORGE_HOME/#~/${HOME}}"
        # Archive everything in CONDA_BLD_PATH except environments
        # Archive the CONDA_BLD_PATH environments only when the job fails
        # Use different prefix for successful and failed build artifacts
        # so random failures don't prevent rebuilds from creating artifacts.
        if [ $JOB_STATUS == "failure" ]; then
          export BLD_ARTIFACT_PREFIX="conda_artifacts"
          export ENV_ARTIFACT_PREFIX="conda_envs"
        else
          export BLD_ARTIFACT_PREFIX="conda_pkgs"
        fi
        if [ $OS == "windows" ]; then
          pwsh -Command ". '.scripts/create_conda_build_artifacts.bat'"
        else
          ./.scripts/create_conda_build_artifacts.sh
        fi

    - name: Store conda build artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: ${{ always() && steps.prepare-artifacts.outcome == 'success' }}
      with:
        name: ${{ steps.prepare-artifacts.outputs.BLD_ARTIFACT_NAME }}
        path: ${{ steps.prepare-artifacts.outputs.BLD_ARTIFACT_PATH }}
        retention-days: 14
      continue-on-error: true

    - name: Store conda build environment artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      # only relevant if build failed, see above
      if: ${{ always() && steps.determine-status.outputs.status == 'failure' && steps.prepare-artifacts.outcome == 'success' }}
      with:
        name: ${{ steps.prepare-artifacts.outputs.ENV_ARTIFACT_NAME }}
        path: ${{ steps.prepare-artifacts.outputs.ENV_ARTIFACT_PATH }}
        retention-days: 14
      continue-on-error: true