name: 'Make Test'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - base-installer-support
jobs:
  # Check/fix formatting first, then check/fix hashes.
  check-formatting-and-hashes:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    name: C/C++ formatting & hashes
    container:
      image: 'gnuradio/ci:ci-format-and-hash-debian-13-3.x'
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Add git repo to safe repos
      run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
    - name: Run clang-format 22 on in-tree C/C++ files
      run: >
          git ls-files -z |
          grep -i -E -z '\.(c|h|cc|cpp|cxx|hpp|hh)$' |
          xargs -0 clang-format-22 -i
    - name: get changed files after formatting
      shell: bash
      run: >
          git --no-pager diff -z --name-only --
          > /tmp/formatdiff
          ; [[ ! -s /tmp/formatdiff ]] && exit 0
          ; printf '::error::Some files changed when formatted with clang-format-22!\n'
          ; printf '::group::Files with changes\n'
          ; sed -z 's;.*;::notice file=&::Formatting change in &\n;' /tmp/formatdiff
          | tr -d '\0'
          ; printf '::endgroup::\n'
          ; exit -1
    - name: Run hash fixer on all binding files
      shell: bash
      run: >
          git ls-files -z |
          grep -i -z '/bindings/.*\.cc$' |
          xargs -0 gr-utils/bindtool/scripts/binding-hash-hotfixer.zsh
    - name: get files with changed hashes
      shell: bash
      run: >
          git --no-pager diff -z --name-only --
          > /tmp/hashdiff
          ; [[ ! -s /tmp/hashdiff ]] && exit 0
          ; printf '::error::Some files had wrong hashes!\n'
          ; printf '::group::Files with wrong hashes\n'
          ; sed -z 's;.*;::notice file=&::Hash mismatch in &\n;' /tmp/hashdiff
          | tr -d '\0'
          ; printf '::endgroup::\n'
          ; exit -1

  check-python-formatting:
    name: Check Python Formatting
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - uses: quentinguidee/pep8-action@v1
      with:
        # -----------------------------------
        # UPDATE tox.ini when making changes!
        arguments: '--max-line-length=120 --ignore E265,E266,E275,E402,E501,E704,E712,E713,E714,E711,E721,E722,E741,W504,W605 --exclude *.yml.py'
        # -----------------------------------
  linux-docker:
  # All of these shall depend on the formatting check (needs: checks of formatting and hashes)
    needs: [check-formatting-and-hashes, check-python-formatting]
    runs-on: ubuntu-24.04
    # The GH default is 360 minutes (it's also the max as of Feb-2021). However
    # we should fail sooner. The only reason to exceed this time is if a test
    # hangs.
    timeout-minutes: 120
    strategy:
      # Enabling fail-fast would kill all Dockers if one of them fails. We want
      # maximum output.
      fail-fast: false
      matrix:
        # For every distro we want to test here, add one key 'distro' with a
        # descriptive name, and one key 'containerid' with the name of the
        # container (i.e., what you want to docker-pull)
        include:
          - distro: 'No-Python Ubuntu 24.04'
            containerid: 'gnuradio/ci:ubuntu-24.04-3.10'
            enable_python: Off
          - distro: 'Ubuntu 24.04'
            containerid: 'gnuradio/ci:ubuntu-24.04-3.10'
          - distro: 'Ubuntu 26.10'
            containerid: 'gnuradio/ci:ubuntu-26.10-3.11'
          - distro: 'Fedora 44 (0xFE init,GLIBCXX_ASSERTIONS)'
            containerid: 'gnuradio/ci:fedora-44-3.11'
            cxxflags: -ftrivial-auto-var-init=pattern -Wp,-D_GLIBCXX_ASSERTIONS
            ldpath: /usr/local/lib64
          - distro: 'Fedora 44 (clang,ninja,stack-protector)'
            containerid: 'gnuradio/ci:fedora-44-3.11'
            cxxflags: -Wno-unused-command-line-argument -fstack-protector
            cmakeflags: -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -GNinja
            build_options: --
            ldpath: /usr/local/lib64
          - distro: 'Debian 12 (32-bit)'
            containerid: 'gnuradio/ci:debian-i386-12-3.10'
            containeroptions: '--platform linux/i386'
            ctest_args: '-E "qa_polar_..coder_(sc_)?systematic"'
            ## Skip upload, cause 32 bit node doesn't work
            skip_upload: True
          - distro: 'Debian 13'
            containerid: 'gnuradio/ci:debian-13-3.10'
          - distro: 'Debian 14'
            containerid: 'gnuradio/ci:debian-14-3.11'
    name: ${{ matrix.distro }}
    container:
      image: ${{ matrix.containerid }}
      volumes:
        - build_data:/build
      options: --cpus 4 ${{ matrix.containeroptions }}
    steps:
    - uses: actions/checkout@v1
      name: Checkout Project
    - name: Prepare sccache usage (if available)
      id: enable_sccache
      env:
        SCCACHE_S3_ENDPOINT: ${{ vars.SCCACHE_S3_ENDPOINT }}
        SCCACHE_S3_BUCKET: ${{ vars.SCCACHE_S3_BUCKET }}
        SCCACHE_S3_REGION: ${{ vars.SCCACHE_S3_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SCCACHE_S3_KEY }}
        AWS_ACCESS_KEY_ID: ${{ vars.SCCACHE_S3_KEY_ID }}
      run: .github/ci-tools/setup_cmake_cache_flags.bash "${{ matrix.distro }}"
    - name: CMake
      env:
        CXXFLAGS: ${{ matrix.ignore_errors || '-Werror' }} ${{ matrix.cxxflags }}
      run: >
        cd /build
        && cmake
        -DENABLE_DEFAULT=${{ matrix.enable_default || 'On' }}
        -DENABLE_DOXYGEN=${{ matrix.enable_doxygen || 'Off' }}
        -DENABLE_PYTHON=${{  matrix.enable_python  || 'On' }}
        ${{ steps.enable_sccache.outputs.CXX_LAUNCHER }}
        ${{ steps.enable_sccache.outputs.C_LAUNCHER }}
        ${{ matrix.cmakeflags }}
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        ${GITHUB_WORKSPACE}
    - name: Dump compile commands
      if: ${{ ! matrix.skip_upload }}
      uses: actions/upload-artifact@v4
      with:
        name: '${{ matrix.distro }}.compile_commands.json'
        path: /build/compile_commands.json
        if-no-files-found: ignore
    - name: Build
      run: cmake --build /build ${{ matrix.build_options || '--parallel $(nproc)' }}
    - name: CTest
      env:
        QT_QPA_PLATFORM: offscreen
      run: 'cd /build && ctest --output-on-failure ${{ matrix.ctest_args }} -j2'
    - name: Install
      run: cmake --install /build
    - name: Update dynamic linker directories
      if:  ${{ matrix.ldpath }}
      run: echo "${{ matrix.ldpath }}" >> /etc/ld.so.conf
    - name: ldconfig
      run: ldconfig
    - name: Test Python3
      if: ${{ matrix.enable_python != 'Off' }}
      run: python3 -c "import gnuradio.blocks; print(gnuradio.blocks.complex_to_float())"
    - name: Test gr_modtool (up to build of dummy block)
      if: ${{ matrix.enable_python != 'Off' }}
      run: |
          cd /tmp && \
          gr_modtool newmod testmod && \
          cd gr-testmod && \
          gr_modtool add -l cpp -t sink \
                         --copyright "GR CI" \
                         --argument-list "" \
                         --add-python-qa \
                         --add-cpp-qa \
                         dummy && \
          mkdir build && \
          cd build && \
          cmake .. &&\
          make -j$(nproc)
    - name: Install into bundling directory
      if: ${{ ! matrix.skip_upload }}
      run: cmake --install /build --prefix /target
    - name: Bundle installed files
      if: ${{ ! matrix.skip_upload }}
      run: tools/collect_installation.bash "${{ matrix.distro }}" "/target" "/installation-archive.squash"
    - name: Upload installation archive
      if: ${{ ! matrix.skip_upload }}
      uses: actions/upload-artifact@v4
      with:
        name: '${{ matrix.distro }} installation archive'
        # already much better compressed
        compression-level: 0
        path: /installation-archive.squash
        if-no-files-found: warn
        # these things are kinda large, keep them around for 7 days: we can recreate them if we want
        retention-days: 7
    - name: Check for installation duplicates
      if: ${{ ! matrix.skip_upload }}
      run: tools/check_installation_duplicates.bash /build/install_manifest.txt
    - name: Show final sccache and build directory stats
      if: always()
      continue-on-error: true
      shell: bash
      run: ./.github/ci-tools/build-summary.sh "${{ matrix.distro }}" "/build"
